### ISSUE TITLE
500 server error when submitting form

### ISSUE THREAD

**Issue by yangcs907** [c21u/blockcerts-admin-app#22]
Filled out form, returned server error (500)
Linked used was https://admin.blockcerts.gatech.edu/7CC165/add_person/

**Comment by stuartf** [comment]
This happens when the form fails server side validation, it 500s because we don't actually return anything. We should actually return a 400 with a message like invalid input. We should also use something like https://www.agiliq.com/blog/2013/02/easy-client-side-form-validations-for-django-djang/ to do client side validation so that the form won't post with bad data.
